baseURL = "https://clarividentedaltonico.github.io/clarividente-daltonico/"
languageCode = "es"
title = "clarividente dalt√≥nico"
theme = "cupper"

disableKinds = ["taxonomy", "term"]

[params]
  googleAnalytics = ""
  customCSS = ["css/custom.css"]
