baseURL = "https://clarividentedaltonico.github.io/clarividente-daltonico/"
languageCode = "es"
title = "Clarividente Dalt√≥nico"
theme = "PaperMod"

publishDir = "docs"

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
