baseURL = "http://localhost:1313/"
languageCode = "es"
title = "clarividente dalt√≥nico"
theme = "cupper"

disableKinds = ["taxonomy", "term"]

[params]
  googleAnalytics = ""
  customCSS = ["css/custom.css"]
